### PR TITLE
Add format_timedelta(format='narrow') support

### PR DESCRIPTION
**Pull request by moreati**
e.g.
```python
>>> format_timedelta(timedelta(hours=3), format='short', locale='en')
u'3 hrs'
>>> format_timedelta(timedelta(hours=3), format='narrow', locale='en')
u'3h'
>>> print format_timedelta(timedelta(hours=3), format='short', locale='gu_IN')
3 કલાક
>>> print format_timedelta(timedelta(hours=3), format='narrow', locale='gu_IN')
3 ક
```

### CODE REVIEW

**Comment by sils1297** [comment]
@moreati could you see to it that our tests pass (and then that your code is covered by it)? The checks have to pass in order for us to review and merge this PR.

**Comment by moreati** [comment]
Sorry for that. Last minute, late night tweak. Thought I'd run it through tox.

**Comment by sils1297** [comment]
@moreati could you squash the commits? Both represent one change together and are easier to maintain (blame, revert, bisect...) when squashed.

**Comment by sils1297** [comment]
@moreati ping me if you need any assistance.

**Comment by sils1297** [comment]
@moreati many thanks! Will merge after CI approval. This won't be backported as it's a new feature.

**Comment by moreati** [comment]
> I'm not sure if `narrow` is the right expression for that.

It's the term used by [CLDR](http://cldr.unicode.org/translation/units) - ditto for the existing values: `short`, and `long`

**Comment by moreati** [comment]
That codecov regression isn't strictly related to having format='narrow' - the innards of that if block already weren't covered. Do you want it fixed in this pull request? If so do you want the commit squashed?

**Comment by sils1297** [comment]
> It's the term used by CLDR - ditto for the existing values: short, and long

alright

**Comment by sils1297** [comment]
@moreati yes please add a check but in an own commit as this change makes sense without the other and they're orthogonal and atomic IMO.

**Comment by sils1297** [comment]
that sentence got chaotic... this test is not explicitly bound to your change and thus it could be considered an atomic change and therefore is fine in another commit :)

**Pull request merged**
