### PR TITLE
allow utf8 BOM + magic comment, closes #189

### LINKED ISSUE #189: crash reading file with UTF-8 BOM + "# coding: utf-8" (supported since python 2.5)
Reading such a file fails at

https://github.com/mitsuhiko/babel/blob/master/babel/util.py#L81

however, those files seem to be supported since 2.5:

https://bugs.python.org/issue1378022

Would you consider a patch to allow such files in babel?

Thanks!

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by sils1297** [comment]
@lepistone hey, I did a short review, thanks for taking the time to submit this PR! Greatly appreciated :)

Ping us if you need any help improving.

**Comment by lepistone** [comment]
Thanks for the review! Ok, I'll improve the commentary and the broken link.

**Comment by sils1297** [comment]
Note that CI only failed because I restarted the build and codecov has an infrastructural issue, not a problem for this PR. I contacted the support already. The build was fine before and will be again when codecov fixes this :)

**Comment by erickwilder** [comment]
@lepistone 
We really appreciate to have more contributions approved in a short time frame. Let me know if you need help on this.

Thanks again for you contribution :+1:

**Comment by lepistone** [comment]
@erickwilder you're right, sorry for the delay. I updated the dead link instead of deleting it and proposed a different error message. (I had to rebase to delete my broken commit where I deleted the link to the language reference).

Thanks!

**Comment by lepistone** [comment]
Hurm, actually I answered a comment on a commit that I rebased. Here it is: https://github.com/lepistone/babel/commit/efe39c1ee063d522ba1e39bcb25ef375dd0f2696#commitcomment-12882619

**Comment by lepistone** [comment]
Do you think this needs more work? Thanks!

**Comment by sils1297** [comment]
@lepistone sorry, I'm on holidays, mostly without internet connection. Review will happen soon one way or another, promised :)

@erickwilder didn't you want to merge a few PRs last week? Would be nice if you could at least relabel PRs appropriately so I know where I can look at when I'm home after ownCloud conference.

**Comment by lepistone** [comment]
no problem, thanks!

**Pull request merged**
