### PR TITLE
Fix typo on mapping filename

### PR DESCRIPTION
**Pull request by jespino**
Now the setup.cfg example for extract_messages configuration is equivalent to the command line example.

### CODE REVIEW

**Comment by sils1297** [comment]
@jespino hey, can you rebase this PR? IIRC there was a time where tests failed on master, maybe this will fix CI for this PR.

Thanks for submitting!

**Comment by jespino** [comment]
Rebased! :smile:

**Comment by sils1297** [comment]
@jespino many thanks! Tests pass, scheduled for review!

**Comment by erickwilder** [comment]
:+1:

**Comment by sils1297** [comment]
@erickwilder is that an approval? Can you merge then? Do I have to review still?

**Comment by erickwilder** [comment]
@sils1297 
Sorry, I was in my phone (and, yes it was an approval ^^)

**Pull request merged**
