### PR TITLE
New header 'Language'

### PR DESCRIPTION
**Pull request by jrfern**
A (possible) fix for bug ticket 76. Adds header field 'Language', which was introduced in gettext in 2010.

### CODE REVIEW

**Comment by jrfern** [comment]
Explanation, comments, etc. on issue no. 76
https://github.com/mitsuhiko/babel/issues/76

**Comment by sils1297** [comment]
@jrfern thanks for submitting a PR! Can you rebase it? That should fix the tests.

**Comment by jrfern** [comment]
On holidays, I 'll be back soon

**Comment by sils1297** [comment]
@jrfern ping me if you need any assistance! Thanks!

**Pull request closed without merging**
