### PR TITLE
Backporting #174 bugfix to 2.x version

### LINKED ISSUE #174: Locale.parse('zh_CN') raises a TypeError on Babel 2.0 with Python 3.3 and 3.4.
```
Python 3.4.3 (default, Apr 13 2015, 22:30:47)
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> babel.__version__
'2.0'
>>> from babel.core import Locale
>>> Locale.parse('zh_CN')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/py34/lib/python3.4/site-packages/babel/core.py", line 286, in parse
    language = get_global('language_aliases').get(language, language)
  File "/venv/py34/lib/python3.4/site-packages/babel/core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
>>>
```
`Locale.parse('zh_CN')` should work and load `zh_CN` localedata.

On Python 2.7, it works fine.
```
Python 2.7.3 (default, Jun 22 2015, 19:33:41)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> babel.__version__
'2.0'
>>> from babel.core import Locale
>>> Locale.parse('zh_CN')
Locale('zh', territory='CN', script='Hans')
>>>
```

### PR DESCRIPTION
**Pull request by erickwilder**
This pull request is intended to backport the changes made by @jun66j5 to fix #174, please, refer to the original issue for more information:

- https://github.com/mitsuhiko/babel/issues/174
- https://github.com/mitsuhiko/babel/pull/188

### CODE REVIEW

**Comment by sils1297** [comment]
The AppVeyor configuration isn't backported yet.

**Comment by erickwilder** [comment]
I would wait until we get https://github.com/mitsuhiko/babel/pull/197 approved before merging this so we can take advantage of better CI reports
@sils1297 can we follow that strategy?

**Comment by sils1297** [comment]
Sure.
Am 06.08.2015 6:57 nachm. schrieb "Erick Wilder" <notifications@github.com>:

**Comment by kruton** [comment]
Looks like the other change was merged. Is this ready to go in then?

**Comment by erickwilder** [comment]
@kruton 
You're right. I'll make a double check here to see if I'm not missing anything.

**Pull request merged**
