### PR TITLE
Support 'Language' header field of PO files

### PR DESCRIPTION
**Pull request by felixonmars**
I only adjusted the tests based on @dmbasso's branch. Let me know if anything else is needed to get this merged.

### CODE REVIEW

**Comment by sils1297** [comment]
hey, the tests and the feature belong together, right? So could you squash the commits? (You can use `git rebase --interactive`)

Also this needs a rebase which will probably fix the tests.

Can you adjust your commit message so it explains the change and not the fix? Is there any issue? Please place a reference to the issue describing the problem. If there is no issue, could you create one?

More information about a good commit message style is available on http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages .

**Comment by felixonmars** [comment]
Hi, thanks for the hint :)

I have squashed the commits and rebased to current master. Please let me know if anything is still missing, thanks!

**Comment by sils1297** [comment]
lgtm, @erickwilder can you take a short look and merge?

**Comment by erickwilder** [comment]
Looks good

**Pull request merged**
