### PR TITLE
Fixed issue #109: `ImportWarning` warned when `import babel`

### PR DESCRIPTION
**Pull request by philiptzou**
`localedata.py` uses the same name with folder `localedata/`, which
Python will try to load `localdata/__init__.py` and warn `ImportWarning`
if the file not found.

If try to filter the `ImportWarning` as an error like this:

```python
import warnings
warnings.filterwarnings('error', category=ImportWarning)
import babel
```

An `ImportWarning` exception will be raised.

### CODE REVIEW

**Comment by philiptzou** [comment]
@sils1297: I create this pull request instead of updating #160 since I can't modify voleg/babel.

**Comment by philiptzou** [comment]
@sils1297 The missed newline fixed

**Comment by sils1297** [comment]
@philiptzou cool, thanks! I'll get this reviewed by tommorrow.

**Comment by sils1297** [comment]
@philiptzou looks good to me on first sight. If I might suggest a new commit message:

```
localedata.py: Move to localedata/__init__.py

`localedata.py` uses the same name with folder `localedata/`, which
Python will try to load `localdata/__init__.py` and warn `ImportWarning`
if the file not found.

Fixes https://github.com/mitsuhiko/babel/issues/109
```

@erickwilder can you take a look if this violates anything existent in this project? I'm not that much into it yet. Also we need to agree on commit message guidelines at some point.

**Comment by sils1297** [comment]
@philiptzou also, if you have a few minutes left - could you add a test for this?

**Comment by sils1297** [comment]
@philiptzou sorry for this inconvenience: we have added major changes to the continuous integration services. Can you please rebase so they get triggered?

**Comment by erickwilder** [comment]
@sils1297
It's ok for me. Whenever possible we need to add tests. @philiptzou can you add some?

**Comment by sils1297** [comment]
Ok @philiptzou following stuff needs to be done:

1. Rebase onto current master.
2. Change commit message. (Describe change, not only bug number.)
3. Add a test (in an own commit) that would have failed before your commit.
4. Push it up.
5. We'll take a last look and merge it :)

**Comment by philiptzou** [comment]
To be honest I don't think a unit test is required. This pull-request is just moved `babel/localedata.py` → `babel/localedata/__init__.py` and correspondingly changed the `_dirname` value. If there's an error or failure, the `babel.localedata` module would not be imported properly, and an `ImportError` would be likely raised. But this doesn't happen to every exist test. So we can say this changes has already been covered by other exist tests.

**Comment by erickwilder** [comment]
@philiptzou ok. I'm fine with this. Can we merge @sils1297?

**Pull request merged**
